name: gd_store
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  auto_route: ^9.2.2
  auto_route_generator: ^9.0.0
  cached_network_image: ^3.4.1
  cloud_firestore: ^5.4.1
  dio: ^5.7.0
  firebase_auth: ^5.2.1
  firebase_core: ^3.4.1
  firebase_storage: ^12.3.0
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.4
  go_router: ^14.2.7
  hooks_riverpod: ^2.5.2
  image: ^4.2.0
  image_picker: ^1.1.2
  json_annotation: ^4.9.0
  uuid: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  freezed: ^2.5.2
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  assets:
  - assets/fonts/
  - assets/profile_image.jpg
  - assets/profile_image.png

  fonts:
    - family: General Sans
      fonts:
        - asset: assets/fonts/general_sans/GeneralSans-Bold.otf
          weight: 700

        - asset: assets/fonts/general_sans/GeneralSans-Semibold.otf
          weight: 600

        - asset: assets/fonts/general_sans/GeneralSans-Medium.otf
          weight: 500

        - asset: assets/fonts/general_sans/GeneralSans-Regular.otf
          weight: 400
          
        - asset: assets/fonts/general_sans/GeneralSans-Light.otf
          weight: 300

        - asset: assets/fonts/general_sans/GeneralSans-Extralight.otf
          weight: 200

    - family: Athletics
      fonts:
        - asset: assets/fonts/athletics/Athletics-Black.otf
          weight: 900

        - asset: assets/fonts/athletics/Athletics-ExtraBold.otf
          weight: 800

        - asset: assets/fonts/athletics/Athletics-Bold.otf
          weight: 700

        - asset: assets/fonts/athletics/Athletics-Medium.otf
          weight: 500

        - asset: assets/fonts/athletics/Athletics-Regular.otf
          weight: 400

        - asset: assets/fonts/athletics/Athletics-Light.otf
          weight: 300


